# -*- coding: utf-8 -*-
"""pdf_chat.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YYxXXZskX0RMYDPUTjOALR0IfKIDx4pG
"""

!pip install langchain-huggingface langchain-groq sentence-transformers chromadb
!pip install -U langchain langchainhub
!pip install langchain-community

from google.colab import userdata
import os

os.environ['GROQ_API_KEY'] = userdata.get('chatApi')

!pip install pypdf

from langchain_community.document_loaders import PyPDFLoader
from pathlib import Path

def load_pdfs(folder_path):
    all_documents = []
    pdf_files = list(Path(folder_path).glob("*.pdf"))

    for pdf_path in pdf_files:
        print(f"Loading: {pdf_path.name}")
        loader = PyPDFLoader(str(pdf_path))
        documents = loader.load()
        all_documents.extend(documents)
        print(f"  ✅ {len(documents)} pages loaded")

    print(f"\nTotal pages loaded: {len(all_documents)}")
    return all_documents

documents = load_pdfs("/content/pdf")

from langchain_text_splitters import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=200)
splits = text_splitter.split_documents(documents)

print(splits[10])

# Free embeddings — no API key needed
from langchain_huggingface import HuggingFaceEmbeddings

embeddings = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")

# Free vector store
from langchain_community.vectorstores import Chroma

vectorstore = Chroma.from_documents(
    documents=splits,
    embedding=embeddings
)

print(vectorstore._collection.count())

print(vectorstore._collection.get())

print("\n collection1 -",vectorstore._collection.get(ids=["16effb4e-c174-4b5d-8a5e-f2aa4053c704"] , include=["embeddings","documents"]))

# for retrieval
retriever = vectorstore.as_retriever()

from langchain_core.prompts import ChatPromptTemplate

prompt = ChatPromptTemplate.from_template("""
You are an assistant for question-answering tasks.
Use the following pieces of retrieved context to answer the question.
If you don't know the answer, just say that you don't know.
Keep the answer simple and consice as possible.
also provide some explanation in needed.
Context: {context}

Question: {question}

Answer:
""")

# now setting up the llm
from langchain_groq import ChatGroq

llm = ChatGroq(
    model="llama-3.3-70b-versatile",  # updated model
    temperature=0,
    api_key=os.environ['GROQ_API_KEY']
)
print(llm.model_name)

from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser

def format_docs(docs):
    return "\n\n".join(doc.page_content for doc in docs)

retriever = vectorstore.as_retriever()

rag_chain = (
    {"context": retriever | format_docs, "question": RunnablePassthrough()}
    | prompt
    | llm
    | StrOutputParser()
)

from google.colab import userdata
import os

os.environ['GROQ_API_KEY'] = userdata.get('chatApi')

key = os.environ.get('GROQ_API_KEY', 'NOT FOUND')
print(f"Key: {key}")
print(f"Starts with gsk_: {key.startswith('gsk_')}")
print(f"Length: {len(key)}")

rag_chain.invoke("what is civil peace?")

rag_chain.invoke("what is life lilke in mountains in nepal")

rag_chain.invoke("who is the writer of tibetian life?")

rag_chain.invoke("explain me about tibetian life in short")

